name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test benchmarks
      run: mkdir build; cd build; cmake ../; make; ./run.sh
    - name: test unittest
      run: mkdir build; cd build; cmake ../; make; make test
