name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build PA1
      run: cd PA1 ; mkdir build ; cd build ; cmake ../ ; make 
    - name: test PA1 benchmarks
      run: cd PA1/build ; ./run.sh
    - name: test PA1 unittest
      run: cd PA1/build ;  make test
    - run: pip3 install numpy  
    - name: build PA2
      run: cd PA2 ; mkdir build ; cd build ; cmake ../ ; make 
    - name: test input_PA2
      run: cd PA2/build ; ./run.sh
    - name: test PA2 unittest
      run: cd PA2/build ;  make test
