name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cd PA1 ; mkdir build ; cd build ; cmake ../ ; make 
    - name: test benchmarks
      run: cd build ; ./run.sh
    - name: test unittest
      run: cd build ;  make test
